Controllers/LeaveAllocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using leave_mgmnt.Contracts;
using leave_mgmnt.Data;
using leave_mgmnt.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace leave_mgmnt.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LeaveAllocationController : Controller
    {
        private readonly ILeaveAllocationRepository _leaveAllocationRepo;
        private readonly ILeaveTypeRepository _leaveTypeRepo;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;

        public LeaveAllocationController(UserManager<Employee> userManager,ILeaveAllocationRepository leaveAllocationRepo, ILeaveTypeRepository leaveTypeRepo,IMapper mapper)
        {
            _leaveAllocationRepo = leaveAllocationRepo;
            _leaveTypeRepo = leaveTypeRepo;
            _userManager = userManager;
            _mapper = mapper;
        }
        // GET: LeaveAllocationController
        public async Task<ActionResult> Index()
        {
            var leaveType =await _leaveTypeRepo.fndAll();
            var mappedData = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType.ToList());
            var model = new CreateLeaveAllocationVM
            {
                LeaveType = mappedData,
                NumberUpdated = 0
            };
            return View(model);
        }


        public async Task<ActionResult> SetLeave(int id)
        {
            var leaveType = await _leaveTypeRepo.FindById(id);
            var employee = await _userManager.GetUsersInRoleAsync("Employee");

            foreach(var emp in employee)
            {
                if (await _leaveAllocationRepo.isLeaveExiss(id, emp.Id))
                    continue;
                var allocation = new LeaveAllocationVM
                {
                    DateCreated = DateTime.Now,
                    EmployeeId = emp.Id,
                    leaveId = id,
                    NumberOfDays = leaveType.DefaultDays,
                    Period = DateTime.Now.Year
                };
                var leaveAllocation = _mapper.Map<LeaveAllocation>(allocation);
                await _leaveAllocationRepo.Create(leaveAllocation);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> listEmployees()
        {
            var employee = await _userManager.GetUsersInRoleAsync("Employee");
            var model = _mapper.Map<List<EmployeeVM>>(employee);
            return View(model);
        }
        // GET: LeaveAllocationController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var employeeData = _mapper.Map<EmployeeVM>(await _userManager.FindByIdAsync(id));
            var allocation =_mapper.Map<List<LeaveAllocationVM>>( await _leaveAllocationRepo.getLeaveAllocationDetail(id));
            var model = new viewLeaveAllocationVM
            {
                employee = employeeData,
               // employeeId = id,
                leaveAllocation = allocation
            };

            return View(model);
        }

        // GET: LeaveAllocationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveAllocationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LeaveAllocationController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var editData = await _leaveAllocationRepo.FindById(id);
            var model = _mapper.Map<EditLeaveAllocationVM>(editData);
            return View(model);
        }

        // POST: LeaveAllocationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditLeaveAllocationVM data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var record = await _leaveAllocationRepo.FindById(data.Id);
                    record.NumberOfDays = data.NumberOfDays;
                    var isSuccess =await  _leaveAllocationRepo.Update(record);
                    
                    if (!isSuccess)
                    { 
                        ModelState.AddModelError("", "Something went wrong...");
                        return View(data);
                    }
                    return RedirectToAction(nameof(Details),new { id=data.EmployeeId});
                }
                else
                {
                    return View(data);
                }
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(data);
            }
        }

        // GET: LeaveAllocationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeaveAllocationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/LeaveTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using leave_mgmnt.Contracts;
using leave_mgmnt.Data;
using leave_mgmnt.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace leave_mgmnt.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class LeaveTypeController : Controller
    {
        private readonly ILeaveTypeRepository _repo;
        private readonly IMapper _mapper;

        
        public LeaveTypeController(ILeaveTypeRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: LeaveTypeController
       
        public async Task<ActionResult> Index()
        {
            var leaveType =await _repo.fndAll();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType.ToList());
            return View(model);
        }

        // GET: LeaveTypeController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (await _repo.isExists(id))
            {
                var leavetype = await _repo.FindById(id);
                var model = _mapper.Map<LeaveTypeVM>(leavetype);
                return View(model);
            }
            else
            {
                return NotFound();
            }
            
        }

        // GET: LeaveTypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LeaveTypeVM collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var leaveType = _mapper.Map<LeaveType>(collection);
                    leaveType.DateCreated = DateTime.Now;
                    var isSuccess =await _repo.Create(leaveType);
                    if (!isSuccess)
                    {
                        ModelState.AddModelError("", "Something went wrong...");
                        return View(collection);
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(collection);
                }
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(collection);
            }
        }

        // GET: LeaveTypeController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (await _repo.isExists(id))
            {
                var leaveType =await _repo.FindById(id);
                var model = _mapper.Map<LeaveTypeVM>(leaveType);
                return View(model);
            }
            else
            {
                return NotFound();
            }
        }

        // POST: LeaveTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LeaveTypeVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var leaveType = _mapper.Map<LeaveType>(model);
                   
                    var isSuccess = await _repo.Update(leaveType);
                    if (!isSuccess)
                    {
                        ModelState.AddModelError("", "Something went wrong...");
                        return View(model);
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: LeaveTypeController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var leavetype = await _repo.FindById(id);
            if (leavetype == null)
            {
                return NotFound();
            }
            var isSuccess = await _repo.Delete(leavetype);

            if (!isSuccess)
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View();
            }
            return RedirectToAction(nameof(Index));

        }

        // POST: LeaveTypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id,LeaveTypeVM collection)
        {
            try
            {

                var leavetype =await _repo.FindById(id);
                if (leavetype == null)
                {
                    return NotFound();
                }
                var isSuccess = await _repo.Delete(leavetype);
                
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(collection);
                }
                return RedirectToAction(nameof(Index));

              
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(collection);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using leave_mgmnt.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leave Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Leave Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <li class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LeaveRequest" asp-action="Create">Apply For Leave</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LeaveRequest" asp-action="MyLeave">My Leave</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {

                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle " href="#" id="navbarDropDownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage
                                    </a>

                                    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropDownMenuLink">
                                        <a class="dropdown-item text-white bg-dark" asp-controller="LeaveType" asp-action="index">Leave Types</a>
                                        <a class="dropdown-item text-white bg-dark" asp-controller="LeaveAllocation" asp-action="index">Leave Allocations</a>
                                        <a class="dropdown-item text-white bg-dark" asp-controller="LeaveRequest" asp-action="index">Leave Applications</a>
                                        <a class="dropdown-item text-white bg-dark" asp-controller="LeaveAllocation" asp-action="listEmployees">Employees</a>
                                    </div>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Leave Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>